### ISSUE TITLE
defx_git#indicators issue

### ISSUE THREAD

**Issue by blayz3r** [kristijanhusak/defx-git#15]
# Problems summary

:Defx command produces blank buffer on first try, works on second try

## Environment Information

 * OS: Windows 10

 * neovim/Vim version:
![image](https://user-images.githubusercontent.com/12205650/71385949-66f89a00-25b8-11ea-8ef3-d3ca431c394f.png)

**VIMRC**
```vim
call plug#begin('~/.vim/bundle') "plugins' root path

Plug 'Shougo/defx.nvim'
Plug 'kristijanhusak/defx-icons'
Plug 'kristijanhusak/defx-git'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'


" All of your Plugs must be added before the following line
call plug#end()            " required
```

## Screen shot (if possible) 

first time(**blank**)
![image](https://user-images.githubusercontent.com/12205650/71385810-b094b500-25b7-11ea-8361-47626232cdd2.png)

Second time(**works**):
![image](https://user-images.githubusercontent.com/12205650/71386616-0750bd80-25bd-11ea-841c-b9432f9a8d8e.png)

**Log**
![image](https://user-images.githubusercontent.com/12205650/71389219-8a781080-25c9-11ea-8e98-5fe92f84b6d2.png)

**Comment by kristijanhusak** [comment]
@blayz3r I pushed a fix. Please give it a try and let me know if it works now.

**Comment by blayz3r** [comment]
Will do in a couple of days. Currently off the grid

**Comment by blayz3r** [comment]
Works now but issue fixed by https://github.com/kristijanhusak/defx-git/pull/12 is back

**Comment by kristijanhusak** [comment]
That's strange, I didn't change anything around that code. @jjohnson338 sorry for pulling you in, but do you know why your fix https://github.com/kristijanhusak/defx-git/pull/12 doesn't work any more?

**Comment by jjohnson338** [comment]
@kristijanhusak I've kept updated to the latest release on my work PC (using neovim on Windows). I've not experienced any issues with #12 since the pull request was merged. I'll see if I can replicate the reporter's setup. Might be able to replicate the issue then?

**Comment by kristijanhusak** [comment]
@jjohnson338 try using latest pynvim i guess.

**Comment by jjohnson338** [comment]
I've updated `pynvim` to the latest version and still I'm not having issues. I've tested on my home Windows PC (admittedly has a nearly identical setup as my work PC). Still unable to replicate the issue:
![image](https://user-images.githubusercontent.com/1017310/71676005-1407ab00-2d4d-11ea-8d03-85fe8d98d1f0.png)

Software Versions:
Python: 3.8.1
pynvim: 0.4.0
NeoVim: 0.4.3

@blayz3r Is there anything out of the ordinary in `:CheckHealth`?

Also dunno if it's relevant, but have you run `:UpdateRemotePlugins` lately?

**Comment by blayz3r** [comment]
> I've updated `pynvim` to the latest version and still I'm not having issues. I've tested on my home Windows PC (admittedly has a nearly identical setup as my work PC). Still unable to replicate the issue:
> ![image](https://user-images.githubusercontent.com/1017310/71676005-1407ab00-2d4d-11ea-8d03-85fe8d98d1f0.png)
> 
> Software Versions:
> Python: 3.8.1
> pynvim: 0.4.0
> NeoVim: 0.4.3
> 
> @blayz3r Is there anything out of the ordinary in `:CheckHealth`?
> 
> Also dunno if it's relevant, but have you run `:UpdateRemotePlugins` lately?

Sorry I may not have been clear, but the issue is on Windows with **Vim(not Neovim)**

**Comment by jjohnson338** [comment]
@blayz3r  I'm having trouble trying to get vanilla `vim` working in a windows env with Python support. 

I've taken a look into the `git.py` source code. The stack trace you posted above has it breaking at line :31 which is just the end of an object declaration (no funky hidden characters or anything). I see the location of file you were editing exists on a non-C drive. I'll give editing a git repo on a non-C drive a shot to see if it is the cause of your issues?

Update:
Not looking like that causes any issues on my machine.

**Comment by blayz3r** [comment]
I reinstalled Defx-git and it works now so I dunno.
